ComITLibraryMVC/Models/ErrorViewModel.cs
using System;

namespace ComITLibraryMVC.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ComITLibraryMVC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using ComITLibraryMVC.Models;

namespace ComITLibraryMVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ComITLibraryMVC/Controllers/WordController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using WordGuess.Models;

namespace ComITLibraryMVC.Controllers
{
    public  class WordController : Controller
    {
        private static WordGuess.WordGuessSystem _library;
        
        public WordController(WordGuess.WordGuessSystem library)
        {
           _library = library;
        }

        public IActionResult Index()
        {
            var words = _library.GetAllWords();
            return View(words);
        }

        [HttpGet]
        public IActionResult Form(){
            return View();
        }
        
        [HttpGet]
        public IActionResult Game(Word selectedWord){
            Word gameWord = new Word();
            if(selectedWord.Value is null){
                var wordIndex = _library.RandomNumber(1);
                List<Word> wordList = _library.GetAllWords();
                gameWord.InitialWord = selectedWord.Value;
                gameWord = _library.HideLetters(wordIndex, wordList);
                gameWord.NoOfTries =  gameWord.Value.Count();
            } 
            else{
                gameWord.Category = selectedWord.Category;
                gameWord.InitialWord = selectedWord.InitialWord;
                gameWord.Value = selectedWord.Value;
                gameWord.NoOfTries = selectedWord.NoOfTries;
            }     
            return View(gameWord);            
        }

        [HttpPost]
        public IActionResult Enter(Word selectedWord){
            int NoOfTries = selectedWord.NoOfTries;
            char letter = selectedWord.Letter;
            Word newWord = new Word();
            newWord.Category = selectedWord.Category;
            newWord.InitialWord = selectedWord.InitialWord;
            selectedWord.NoOfTries = selectedWord.NoOfTries-1; 
            
            if(letter =='\0')
            {  newWord=selectedWord;
               newWord.Message ="You typed no letter!";
               newWord.NoOfTries=NoOfTries;
               newWord.Value = selectedWord.Value;
            }
            else
            {
                Boolean letterFound = _library.FindLetterInWord(letter, selectedWord);
                
                 
                if(selectedWord.NoOfTries<=0 && !letterFound)
                {
                    newWord=selectedWord;
                    newWord.Message ="Sorry, maybe next time. Press Game to play again";
                    newWord.NoOfTries=0;
                }
                else 
                {
                    if (!letterFound)
                    {
                        newWord=selectedWord;
                        newWord.Message ="Missed....";
                    }
                    else 
                    {
                        newWord = _library.exposeLetters(letter, selectedWord, selectedWord.Value);
                        if(newWord.Value==newWord.InitialWord)
                        {
                        newWord.Message = "WOW....You have found a word. CONGRATS! Press WORDGAME to play again.";
                        newWord.NoOfTries = 0;  
                        }
                        else 
                        {
                        newWord.Message = "Congratulations, you have found a letter!";
                        }
                                    
                    }
                }
            }
      
        return View("Game", newWord);

        }


        [HttpPost]
        public IActionResult Create(Word newWord){
            _library.AddNewWord(newWord);
            return RedirectToAction("Index");
        }

        // [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        // public IActionResult Error()
        // {
        //     return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        // }
    }
}



//   if (letterFound){
//                newWord = _library.exposeLetters(letter, selectedWord, selectedWord.Value);
//                newWord.Message = "Congratulations, you have found a letter!.";
//                newWord.NoOfTries = NoOfTries-1;
//             }
//             else {
//                 if(selectedWord.NoOfTries > 0 )
//                 {
//                     newWord=selectedWord;
//                     newWord.Message ="Missed....";
//                     newWord.NoOfTries = NoOfTries-1;
//                 }
//                else if(selectedWord.NoOfTries == 0 )
//                 {
//                     newWord=selectedWord;
//                     newWord.Message ="Sorry, maybe next time. Press Game to play again";
//                 }
                
//             }
//         return View("Game", newWord);

//         }

ComITLibraryMVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<body>
<div class="body">
    <link rel="stylesheet" type="text/css" href="../css/style.css">
    
        <header class="header">
        <h1>Adam Rybak Personal Page</h1>
        <h1>Visit my  <a href="https://www.linkedin.com/in/adam-rybak-19764690/" target="_blank">LinkedIn </a> profile</h1>
        <img src="images/Adam Picture Linkedin.png" style="width:50px;height:60px;">
        <p>&nbsp;</p>   
        </header>
            
        <div class="mainContent">
            <div class="content">	
                    <article class="content-1">	
                        <header>
                            <h2>Welcome to my personal page</a></h2>
                        </header>
                        
                        <footer>
                            <p class="post-from">This was posted on November 2020 by Adam</p>
                        </footer>
                        
                        <content>
                            <p>This is my personal page where I will be sharing my ideas with website developement and systems improvements.</p>
                            <p>As much I love programming and software development, I always find some things that can or need to be improved.</p>
                            <p>This is why this page or some linked pages are under the construction. </p>
                            <p>Thank you for your understanding.</p>
                        </content>
                        
                    </article>
    
                    <article class="content-2">	
                        <header>
                            <h2><a href="#" rel="bookmark" title="Permalink to this POST TITLE">Header post</a></h2>
                        </header>
    
                        <footer>
                            <p class="post-from">This was posted on the Nov 2020 by Adam</p>
                        </footer>
                        
                        <content>
                            <p>I am not sure if you are aware but there are plenty free web site ideas available on internet.</p>
                            <p>I would encourage all of you interested in web designing click <a href="https://themewagon.com/theme_tag/free/" >here</a> to discover free templates.</p>
                                        <p></p>
                            <p></p>
                        </content>                    
                    </article>
            </div>                
                    @* <aside class="sidebar-1">
                        <article>
                        <h2>Visual Studio Code</h2>
                        <p>You are struggling with VS Code? Let me know how can I help?</p>
                        </article>
                    </aside>
                    
                    <aside class="sidebar-2">
                        <article>
                        <h2>CSS and HTML?</h2>
                        <p>This info will be available for you soon.</p>
                        </article>
                    </aside>				
    
                    <aside class="sidebar-3">
                        <article>
                        <h2>SQL?</h2>
                        <p>This is coming.</p>
                        </article>
                    </aside>	 *@
        </div>
        
       
    </div>
</body>

@* <div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div> *@

ComITLibraryMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Word Guess Game </title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="../css/site.css" />
</head>
<body>
    <div class="body">
        <link rel="stylesheet" type="text/css" href="../css/style.css">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Welcome</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Word" asp-action="Game">WORD GAME</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
</div>
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Adam Rybak - <a asp-area="" asp-controller="Home" asp-action="Index">Home</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
    
</body>
</html>

ComITLibraryMVC/Views/Word/Form.cshtml
@model WordGuess.Models.Word;
<div>
    <h2> New Word Form</h2>
    <hr/>
    <p>
        Please enter the following info to add a new word to the library!
    </p>
    <div>
        <form asp-action="Create">
        <div class="form-group">
            <label>Category</label>
            <input type="text" class="form-control"  asp-for="Category">
        </div>
        <div class="form-group">
            <label for="exampleValue">Value</label>
            <input type="text" class="form-control" asp-for="Value">
        </div>
        
        <button type="submit" class="btn btn-primary">Create</button>
        </form>

    </div>
    <br/>
    
</div>

ComITLibraryMVC/Views/Word/Game.cshtml
@using WordGuess.Models
@model WordGuess.Models.Word;

<div>
    <h2>Game ON!</h2>
</div>
<div class="blockquote text-center">
<hr/>
<div>
    <thead>
        
            <h2>Do you think you know words?  Let's check it out, word category is @Model.Category.</h2>
            <p>&nbsp;</p>
            <h2>You have @Model.NoOfTries tries.</h2>
            @* <th scope="col">@Model.Category.</th>
            <th scope="col">You have @Model.NoOfTries tries.</th> *@
        
    </thead>
    <tbody>
        <p>&nbsp;</p>
        
        <tr>            
            <h2>@Model.Value</h2>
        </tr>         
      
    </tbody>
    <p>&nbsp;</p>
         <tr>
            <th scope="col">@Model.Message</th>  
         </tr> 
        <p>&nbsp;</p>
</table>
<table align="center" >
    <form asp-action="Enter" align="center">
        
        <div>
            <div class="input-group-prepend">
                <input type="hidden" value = "@Model.Category" asp-for="@Model.Category">
                <input type="hidden" value = "@Model.Value" asp-for="@Model.Value">
                <input type="hidden" value = "@Model.InitialWord" asp-for="@Model.InitialWord">
                <input type="hidden" value = "@Model.NoOfTries" asp-for="@Model.NoOfTries">
            </div>
            <div class="col-6 col-md-6 offset-md-3">   
                <input type="text" class="form-control" autofocus="autofocus" maxlength="1" placeholder="Enter one letter . . . &#x23ce;" asp-for="Letter" value="" > 
                <button type="submit" class="btn btn-primary">GUESS</button>
            </div>

        </div>


    
    </form>


    
      
    
</table>
</div>
</div>

ComITLibraryMVC/Views/Word/index.cshtml
@using WordGuess.Models
@model List<Word>

<div>
    <h2>List of Words - Admin only.</h2>
</div>

<hr/>
<div>

    <table class="table table-hover">
    <thead>
        <tr>
        <th scope="col">Category</th>
        <th scope="col">Value</th>
        </tr>
    </thead>
    <tbody>
    @for (int i = 0; i < Model.Count; i++)
        {
            <div>
                <tr>
                    <td>@Model[i].Category</td>
                    <td>@Model[i].Value</td>
                </tr>
            </div>
        }   
    </tbody>
</table>

<div>
   <a asp-action="Form" class="btn btn-primary">Create New Word</a>
</div>

<div>
    <a asp-action="Game" class="btn btn-danger">Play Game</a>
</div>
</div>